# Introduction to Numpy - 🐊

In [3]:
import numpy as np

Whereas panda helps sort and work with data. Numpy is for calculations. 

Let's create an array.

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [7]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


Two-dimensions.

In [10]:
c = np.array([[[1], [2], [3]],[[4], [5], [6]]])
print(c)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


We can actually check this with the function ndim.

In [16]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


or we can check the whole shape...

In [17]:
print(a.shape)
print(b.shape)
print(c.shape)

(6,)
(2, 3)
(2, 3, 1)


Your turn: 
Create a Rubik's cube where each color is a number. 

In [14]:
# code

We can also work with pandas and numpy together! 

In [26]:
b = pd.DataFrame([[1, 2, 3],[4, 5, 6]])
b.columns = ['name1','name2','name3'] 
print(b)

   name1  name2  name3
0      1      2      3
1      4      5      6


In [27]:
b.to_numpy()

array([[1, 2, 3],
       [4, 5, 6]])

or a specific column

In [28]:
b['name1'].to_numpy()

array([1, 4])

Now we can do something with the array. 

In [34]:
d = b['name1'].to_numpy()
e = d + 10
print(e)

[11 14]


Let's send it back to pandas.

In [37]:
b['name1'] = pd.array(e)
print(b)

   name1  name2  name3
0     11      2      3
1     14      5      6


Your turn: using your rubrik's cube
* Add a constant to each value
* Send to pandas
* And add columns